import type {
  RoutineWorkflowSettings,
  WorkflowCapabilities,
  WorkflowFieldDefinition,
  WorkflowOperationDefinition,
} from "../../../shared/routine-workflow";
import { ROUTINE_WORKFLOW_VERSION } from "../../../shared/routine-workflow";
import { ROUTINE_WORKFLOW_TEMPLATES } from "./templates";

export const DEFAULT_WORKFLOW_LIMITS: Required<RoutineWorkflowSettings> = {
  maxRunDurationMs: 30 * 60 * 1_000,
  maxStepCount: 100,
  maxForEachItems: 100,
  maxParallelSteps: 4,
  retainStepDataDays: 30,
};

const text = (
  key: string,
  label: string,
  options: Partial<WorkflowFieldDefinition> = {},
): WorkflowFieldDefinition => ({
  key,
  label,
  type: "string",
  supportsVariables: true,
  ...options,
});

const list = (
  key: string,
  label: string,
  options: Partial<WorkflowFieldDefinition> = {},
): WorkflowFieldDefinition => ({
  key,
  label,
  type: "list",
  supportsVariables: true,
  ...options,
});

const bool = (
  key: string,
  label: string,
  options: Partial<WorkflowFieldDefinition> = {},
): WorkflowFieldDefinition => ({
  key,
  label,
  type: "boolean",
  ...options,
});

const select = (
  key: string,
  label: string,
  values: string[],
  options: Partial<WorkflowFieldDefinition> = {},
): WorkflowFieldDefinition => ({
  key,
  label,
  type: "select",
  options: values.map((value) => ({ value, label: value.replace(/_/g, " ") })),
  ...options,
});

const starter = (
  id: string,
  name: string,
  description: string,
  fields: WorkflowFieldDefinition[],
  provider = "CoWork",
  requiredScopes: string[] = [],
  availability: WorkflowOperationDefinition["availability"] = "available",
): WorkflowOperationDefinition => ({
  id,
  kind: "starter",
  category: "Starters",
  provider,
  name,
  description,
  risk: "read",
  fields,
  outputFields: ["event", "timestamp", "source"],
  requiredScopes,
  availability,
});

const action = (
  definition: Omit<WorkflowOperationDefinition, "kind" | "availability"> & {
    kind?: WorkflowOperationDefinition["kind"];
    availability?: WorkflowOperationDefinition["availability"];
  },
): WorkflowOperationDefinition => ({
  kind: "action",
  availability: definition.toolName ? "requires_connection" : "available",
  ...definition,
});

const GMAIL_READ = "https://www.googleapis.com/auth/gmail.readonly";
const GMAIL_MODIFY = "https://www.googleapis.com/auth/gmail.modify";
const GMAIL_SEND = "https://www.googleapis.com/auth/gmail.send";
const DRIVE = "https://www.googleapis.com/auth/drive";
const SHEETS = "https://www.googleapis.com/auth/spreadsheets";
const DOCS = "https://www.googleapis.com/auth/documents";
const CALENDAR = "https://www.googleapis.com/auth/calendar";
const TASKS = "https://www.googleapis.com/auth/tasks";
const CHAT = "https://www.googleapis.com/auth/chat.messages";

export const WORKFLOW_OPERATION_CATALOG: WorkflowOperationDefinition[] = [
  starter("starter.manual", "Manual", "Run on demand from CoWork.", []),
  starter("starter.schedule", "On a schedule", "Run at a specific time or cadence.", [
    select("scheduleKind", "Schedule type", ["cron", "every", "at"], { required: true }),
    text("expression", "Schedule", { required: true, placeholder: "0 9 * * 1-5" }),
    text("timezone", "Timezone", { required: true, placeholder: "Europe/Istanbul" }),
  ]),
  starter(
    "starter.gmail_message",
    "When I get an email",
    "Start when a matching Gmail message arrives.",
    [
      text("query", "Gmail search", { placeholder: "is:unread has:attachment" }),
      text("from", "From"),
      text("subjectContains", "Subject contains"),
      bool("includeFlowGenerated", "Include flow-generated email"),
    ],
    "Google Workspace",
    [GMAIL_READ],
  ),
  starter(
    "starter.chat_message",
    "When I get a chat message",
    "Start for a Google Chat message.",
    [
      text("spaceName", "Space"),
      text("sender", "Sender"),
      text("textPattern", "Text or regular expression"),
    ],
    "Google Workspace",
    [CHAT],
  ),
  starter(
    "starter.chat_mention",
    "When I am mentioned",
    "Start when the connected user is mentioned.",
    [text("spaceName", "Space")],
    "Google Workspace",
    [CHAT],
    "preview",
  ),
  starter(
    "starter.chat_reaction",
    "When an emoji reaction is added",
    "Start when a matching reaction is added.",
    [text("spaceName", "Space"), text("reaction", "Reaction name")],
    "Google Workspace",
    [CHAT],
    "preview",
  ),
  starter(
    "starter.chat_member_joined",
    "When someone joins a space",
    "Start when a member joins a Chat space.",
    [text("spaceName", "Space", { required: true })],
    "Google Workspace",
    [CHAT],
    "preview",
  ),
  starter(
    "starter.sheet_changed",
    "When a sheet changes",
    "Start when cells or rows change.",
    [
      text("spreadsheetId", "Spreadsheet ID", { required: true }),
      text("range", "Range", { placeholder: "Sheet1!A:Z" }),
    ],
    "Google Workspace",
    [SHEETS],
  ),
  starter(
    "starter.drive_item_added",
    "When an item is added to a folder",
    "Start for a new Drive item.",
    [text("folderId", "Folder ID", { required: true })],
    "Google Workspace",
    [DRIVE],
  ),
  starter(
    "starter.drive_file_edited",
    "When a file is edited",
    "Start when a Drive file changes.",
    [text("fileId", "File ID", { required: true })],
    "Google Workspace",
    [DRIVE],
  ),
  starter(
    "starter.drive_folder_item_edited",
    "When an item in a folder is edited",
    "Start when a direct child changes.",
    [text("folderId", "Folder ID", { required: true })],
    "Google Workspace",
    [DRIVE],
  ),
  starter(
    "starter.meeting_relative",
    "Based on a meeting",
    "Run before or after a matching meeting.",
    [
      select("direction", "Timing", ["before", "after"], { required: true }),
      text("offsetMinutes", "Offset in minutes", { required: true, defaultValue: "15" }),
      text("calendarId", "Calendar ID", { defaultValue: "primary" }),
      text("query", "Meeting title contains"),
    ],
    "Google Workspace",
    [CALENDAR],
  ),
  starter(
    "starter.meeting_outputs_ready",
    "When meeting outputs are ready",
    "Start when notes or a transcript is ready.",
    [select("outputType", "Output", ["notes", "transcript", "either"], { required: true })],
    "Google Workspace",
    [CALENDAR, DRIVE],
  ),
  starter(
    "starter.form_response",
    "When a form response comes in",
    "Start from a linked response sheet or signed webhook.",
    [text("formId", "Form ID"), text("spreadsheetId", "Linked response spreadsheet ID")],
    "Google Workspace",
    [SHEETS],
  ),

  action({
    id: "ai.ask_gemini",
    kind: "ai",
    category: "AI",
    provider: "CoWork AI",
    name: "Ask Gemini",
    description: "Generate a schema-bound answer using the selected model and sources.",
    risk: "read",
    fields: [
      text("prompt", "Prompt", { required: true }),
      select("outputType", "Output", ["text", "list", "json"]),
    ],
    outputFields: ["text", "items", "json"],
    requiredScopes: [],
  }),
  action({
    id: "ai.ask_gem",
    kind: "ai",
    category: "AI",
    provider: "CoWork AI",
    name: "Ask a Gem",
    description: "Run a saved specialist prompt with typed inputs.",
    risk: "read",
    fields: [
      text("gemId", "Gem or agent ID", { required: true }),
      text("prompt", "Prompt", { required: true }),
    ],
    outputFields: ["text", "json"],
    requiredScopes: [],
  }),
  ...[
    ["ai.recap_unread_emails", "Recap unread emails", "Summarize unread Gmail messages."],
    ["ai.extract", "Extract", "Extract structured fields from text or files."],
    ["ai.decide", "Decide", "Return a true or false decision with a reason."],
    ["ai.summarize", "Summarize", "Create a concise summary of supplied content."],
  ].map(([id, name, description]) =>
    action({
      id,
      kind: "ai",
      category: "AI actions",
      provider: "CoWork AI",
      name,
      description,
      risk: "read",
      fields: [text("input", "Input", { required: true })],
      outputFields: id === "ai.decide" ? ["decision", "reason"] : ["text", "items", "json"],
      requiredScopes: id === "ai.recap_unread_emails" ? [GMAIL_READ] : [],
    }),
  ),
  action({
    id: "control.condition",
    kind: "condition",
    category: "Tools",
    provider: "CoWork",
    name: "Check if",
    description: "Route execution through true or false branches.",
    risk: "read",
    fields: [
      text("left", "Value", { required: true }),
      select(
        "operator",
        "Operator",
        [
          "equals",
          "not_equals",
          "contains",
          "not_contains",
          "matches",
          "gt",
          "gte",
          "lt",
          "lte",
          "is_empty",
          "is_not_empty",
        ],
        { required: true },
      ),
      text("right", "Compare with"),
    ],
    outputFields: ["result"],
    requiredScopes: [],
  }),
  action({
    id: "control.filter",
    kind: "filter",
    category: "Tools",
    provider: "CoWork",
    name: "Filter",
    description: "Keep list items matching a condition.",
    risk: "read",
    fields: [
      list("items", "Items", { required: true }),
      text("path", "Item field"),
      select("operator", "Operator", ["equals", "not_equals", "contains", "matches", "gt", "lt"], {
        required: true,
      }),
      text("value", "Compare with"),
    ],
    outputFields: ["items", "count"],
    requiredScopes: [],
  }),
  action({
    id: "control.foreach",
    kind: "foreach",
    category: "Tools",
    provider: "CoWork",
    name: "Repeat for each",
    description: "Run nested actions for a bounded list.",
    risk: "read",
    fields: [
      list("items", "Items", { required: true }),
      text("maxItems", "Maximum items", { defaultValue: "100" }),
    ],
    outputFields: ["items", "results", "count"],
    requiredScopes: [],
  }),
  action({
    id: "notebooklm.ask",
    kind: "ai",
    category: "NotebookLM",
    provider: "Google Workspace",
    name: "Ask NotebookLM",
    description: "Ask a selected notebook when a supported connector is installed.",
    risk: "data_export",
    fields: [
      text("notebookId", "Notebook", { required: true }),
      text("question", "Question", { required: true }),
    ],
    outputFields: ["text", "citations"],
    requiredScopes: [],
    connectorId: "notebooklm",
    availability: "preview",
  }),

  action({
    id: "gmail.notify",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Notify me by email",
    description: "Send an email notification.",
    risk: "external_write",
    fields: [
      text("to", "To", { required: true }),
      text("subject", "Subject", { required: true }),
      text("body", "Message", { required: true }),
    ],
    outputFields: ["messageId", "threadId"],
    requiredScopes: [GMAIL_SEND],
  }),
  action({
    id: "gmail.archive",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Archive",
    description: "Archive a Gmail thread.",
    risk: "external_write",
    fields: [text("threadId", "Thread ID", { required: true })],
    outputFields: ["threadId"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "gmail.draft_email",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Draft email",
    description: "Create a Gmail draft.",
    risk: "external_write",
    fields: [
      text("to", "To", { required: true }),
      text("subject", "Subject", { required: true }),
      text("body", "Body", { required: true }),
    ],
    outputFields: ["draftId", "messageId"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "gmail.draft_reply",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Draft reply",
    description: "Create a draft reply in a thread.",
    risk: "external_write",
    fields: [
      text("messageId", "Message ID", { required: true }),
      text("body", "Body", { required: true }),
    ],
    outputFields: ["draftId", "threadId"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "gmail.add_labels",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Add labels with Gemini",
    description: "Classify and apply Gmail labels.",
    risk: "external_write",
    fields: [
      list("messageIds", "Message IDs", { required: true }),
      list("labels", "Labels", { required: true }),
    ],
    outputFields: ["messageIds", "labels"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "gmail.remove_labels",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Remove labels",
    description: "Remove labels from Gmail messages.",
    risk: "external_write",
    fields: [
      list("messageIds", "Message IDs", { required: true }),
      list("labels", "Labels", { required: true }),
    ],
    outputFields: ["messageIds", "labels"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "gmail.mark_read",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Mark read or unread",
    description: "Set Gmail read state.",
    risk: "external_write",
    fields: [list("messageIds", "Message IDs", { required: true }), bool("read", "Mark as read")],
    outputFields: ["messageIds", "read"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "gmail.star",
    category: "Gmail",
    provider: "Google Workspace",
    name: "Star or remove star",
    description: "Set Gmail starred state.",
    risk: "external_write",
    fields: [list("messageIds", "Message IDs", { required: true }), bool("starred", "Starred")],
    outputFields: ["messageIds", "starred"],
    requiredScopes: [GMAIL_MODIFY],
  }),
  action({
    id: "drive.save_attachments",
    category: "Drive",
    provider: "Google Workspace",
    name: "Add email attachments to Drive",
    description: "Save selected Gmail attachments to Drive.",
    risk: "data_export",
    fields: [
      text("messageId", "Message ID", { required: true }),
      text("folderId", "Folder ID", { required: true }),
    ],
    outputFields: ["files"],
    requiredScopes: [GMAIL_READ, DRIVE],
  }),
  action({
    id: "chat.notify",
    category: "Chat",
    provider: "Google Workspace",
    name: "Notify me in Chat",
    description: "Send a message to a Google Chat space.",
    risk: "external_write",
    fields: [
      text("spaceName", "Space", { required: true }),
      text("text", "Message", { required: true }),
    ],
    outputFields: ["message"],
    requiredScopes: [CHAT],
    connectorId: "google-workspace",
    toolName: "google-workspace.chat_messages_create",
  }),
  action({
    id: "sheets.add_row",
    category: "Sheets",
    provider: "Google Workspace",
    name: "Add a row",
    description: "Append a row to a spreadsheet.",
    risk: "external_write",
    fields: [
      text("spreadsheetId", "Spreadsheet ID", { required: true }),
      text("range", "Range", { required: true }),
      list("values", "Values", { required: true }),
    ],
    outputFields: ["updatedRange", "updates"],
    requiredScopes: [SHEETS],
    connectorId: "google-workspace",
    toolName: "google-workspace.sheets_values_append",
  }),
  action({
    id: "sheets.update_rows",
    category: "Sheets",
    provider: "Google Workspace",
    name: "Update rows",
    description: "Write values to a spreadsheet range.",
    risk: "external_write",
    fields: [
      text("spreadsheetId", "Spreadsheet ID", { required: true }),
      text("range", "Range", { required: true }),
      list("values", "Rows", { required: true }),
    ],
    outputFields: ["updatedRange", "updates"],
    requiredScopes: [SHEETS],
    connectorId: "google-workspace",
    toolName: "google-workspace.sheets_values_update",
  }),
  action({
    id: "sheets.clear_rows",
    category: "Sheets",
    provider: "Google Workspace",
    name: "Clear rows",
    description: "Clear a spreadsheet range.",
    risk: "external_write",
    fields: [
      text("spreadsheetId", "Spreadsheet ID", { required: true }),
      text("range", "Range", { required: true }),
    ],
    outputFields: ["clearedRange"],
    requiredScopes: [SHEETS],
    connectorId: "google-workspace",
    toolName: "google-workspace.sheets_values_clear",
  }),
  action({
    id: "sheets.get_contents",
    category: "Sheets",
    provider: "Google Workspace",
    name: "Get sheet contents",
    description: "Read a spreadsheet range.",
    risk: "read",
    fields: [
      text("spreadsheetId", "Spreadsheet ID", { required: true }),
      text("range", "Range", { required: true }),
    ],
    outputFields: ["values", "range"],
    requiredScopes: [SHEETS],
    connectorId: "google-workspace",
    toolName: "google-workspace.sheets_values_get",
  }),
  action({
    id: "drive.create_folder",
    category: "Drive",
    provider: "Google Workspace",
    name: "Create a folder",
    description: "Create a Drive folder.",
    risk: "external_write",
    fields: [text("name", "Name", { required: true }), text("parentId", "Parent folder ID")],
    outputFields: ["id", "name", "webViewLink"],
    requiredScopes: [DRIVE],
    connectorId: "google-workspace",
    toolName: "google-workspace.drive_folders_create",
  }),
  action({
    id: "calendar.block_time",
    category: "Calendar",
    provider: "Google Workspace",
    name: "Block time",
    description: "Create a calendar event.",
    risk: "external_write",
    fields: [
      text("calendarId", "Calendar ID", { defaultValue: "primary" }),
      text("summary", "Title", { required: true }),
      text("start", "Start", { required: true }),
      text("end", "End", { required: true }),
      text("timeZone", "Timezone"),
    ],
    outputFields: ["event"],
    requiredScopes: [CALENDAR],
    connectorId: "google-workspace",
    toolName: "google-workspace.calendar_event_create",
  }),
  action({
    id: "docs.create",
    category: "Docs",
    provider: "Google Workspace",
    name: "Create a Google doc",
    description: "Create a document with optional content.",
    risk: "external_write",
    fields: [text("title", "Title", { required: true }), text("content", "Content")],
    outputFields: ["documentId", "documentUrl"],
    requiredScopes: [DOCS],
    connectorId: "google-workspace",
    toolName: "google-workspace.docs_create",
  }),
  action({
    id: "docs.append",
    category: "Docs",
    provider: "Google Workspace",
    name: "Add to a doc",
    description: "Append text to a document.",
    risk: "external_write",
    fields: [
      text("documentId", "Document ID", { required: true }),
      text("text", "Text", { required: true }),
    ],
    outputFields: ["documentId", "replies"],
    requiredScopes: [DOCS],
    connectorId: "google-workspace",
    toolName: "google-workspace.docs_append_text",
  }),
  action({
    id: "tasks.create",
    category: "Tasks",
    provider: "Google Workspace",
    name: "Create a task",
    description: "Create a Google Task.",
    risk: "external_write",
    fields: [
      text("tasklist", "Task list ID", { defaultValue: "@default" }),
      text("title", "Title", { required: true }),
      text("notes", "Notes"),
      text("due", "Due date"),
    ],
    outputFields: ["task"],
    requiredScopes: [TASKS],
    connectorId: "google-workspace",
    toolName: "google-workspace.tasks_create",
  }),
  action({
    id: "agent.run",
    kind: "agent",
    category: "CoWork",
    provider: "CoWork",
    name: "Run an agent",
    description: "Delegate a bounded step to a CoWork agent.",
    risk: "local_write",
    fields: [text("prompt", "Instructions", { required: true })],
    outputFields: ["taskId", "status"],
    requiredScopes: [],
  }),
  action({
    id: "asana.create_task",
    category: "Integrations",
    provider: "Asana",
    name: "Asana integration",
    description: "Create a task in Asana.",
    risk: "external_write",
    fields: [
      { key: "data", label: "Task fields", type: "json", required: true, supportsVariables: true },
    ],
    outputFields: ["data", "meta"],
    requiredScopes: [],
    connectorId: "asana",
    toolName: "asana.create_task",
  }),
  action({
    id: "jira.create_issue",
    category: "Integrations",
    provider: "Jira",
    name: "Jira integration",
    description: "Create an issue in Jira.",
    risk: "external_write",
    fields: [
      text("projectKey", "Project key", { required: true }),
      text("issueType", "Issue type", { required: true, defaultValue: "Task" }),
      {
        key: "fields",
        label: "Issue fields",
        type: "json",
        required: true,
        supportsVariables: true,
      },
    ],
    outputFields: ["data", "meta"],
    requiredScopes: [],
    connectorId: "jira",
    toolName: "jira.create_issue",
  }),
  action({
    id: "slack.post_message",
    category: "Integrations",
    provider: "Slack",
    name: "Slack integration",
    description: "Post a message through an installed Slack connector.",
    risk: "external_write",
    fields: [
      text("channel", "Channel", { required: true }),
      text("text", "Message", { required: true }),
    ],
    outputFields: ["data", "message"],
    requiredScopes: [],
    connectorId: "slack",
    toolName: "slack.post_message",
  }),
  action({
    id: "confluence.create_page",
    category: "Integrations",
    provider: "Confluence",
    name: "Confluence integration",
    description: "Create a page when a compatible connector is installed.",
    risk: "external_write",
    fields: [
      text("spaceKey", "Space key", { required: true }),
      text("title", "Title", { required: true }),
      text("body", "Body", { required: true }),
    ],
    outputFields: ["page"],
    requiredScopes: [],
    connectorId: "confluence",
    toolName: "confluence.create_page",
    availability: "preview",
  }),
  action({
    id: "mailchimp.add_contact",
    category: "Integrations",
    provider: "Mailchimp",
    name: "Mailchimp integration",
    description: "Add or update a contact when a compatible connector is installed.",
    risk: "data_export",
    fields: [
      text("audienceId", "Audience ID", { required: true }),
      text("email", "Email", { required: true }),
      { key: "fields", label: "Contact fields", type: "json", supportsVariables: true },
    ],
    outputFields: ["contact"],
    requiredScopes: [],
    connectorId: "mailchimp",
    toolName: "mailchimp.add_contact",
    availability: "preview",
  }),
  action({
    id: "custom.mcp_tool",
    kind: "custom",
    category: "Integrations",
    provider: "MCP",
    name: "Call a connector tool",
    description: "Call an installed MCP tool with validated JSON arguments.",
    risk: "external_write",
    fields: [
      text("toolName", "Tool name", { required: true }),
      {
        key: "arguments",
        label: "Arguments",
        type: "json",
        required: true,
        supportsVariables: true,
      },
    ],
    outputFields: ["content", "result"],
    requiredScopes: [],
  }),
  action({
    id: "custom.webhook",
    kind: "custom",
    category: "Integrations",
    provider: "Web",
    name: "Call a signed webhook",
    description: "Send an HMAC-signed HTTPS request through CoWork network policy.",
    risk: "data_export",
    fields: [
      text("url", "URL", { required: true }),
      select("method", "Method", ["POST", "PUT", "PATCH"], { defaultValue: "POST" }),
      text("secretRef", "Signing secret", {
        required: true,
        supportsVariables: false,
        description: "Stored encrypted; the secret value is never saved in the flow.",
      }),
      { key: "body", label: "Body", type: "json", supportsVariables: true },
    ],
    outputFields: ["status", "ok", "body", "contentType"],
    requiredScopes: [],
  }),
];

export function getWorkflowOperation(operationId: string): WorkflowOperationDefinition | undefined {
  return WORKFLOW_OPERATION_CATALOG.find((operation) => operation.id === operationId);
}

export function getWorkflowCapabilities(): WorkflowCapabilities {
  return {
    version: ROUTINE_WORKFLOW_VERSION,
    operations: WORKFLOW_OPERATION_CATALOG.map((operation) => ({ ...operation })),
    templates: ROUTINE_WORKFLOW_TEMPLATES.map((template) => ({ ...template })),
    limits: { ...DEFAULT_WORKFLOW_LIMITS },
  };
}
